name: build-all

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Git repository to clone'
        required: true
        default: 'https://github.com/jfaltermeier/java-cef.git'
      ref:
        description: 'Git commit id to checkout'
        required: true
        default: 'master'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      build_meta: ${{ env.build_meta }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate release info
        run: |
          cd release_gen
          chmod +x create_release_info.sh
          ./create_release_info.sh ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} ${{github.run_number}} ${{github.repository}}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{env.release_name}}
          tag_name: ${{env.release_tag_name}}
          body_path: release_gen/release_message.md
      - name: Add LICENSE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release_gen/LICENSE
          asset_name: LICENSE
          asset_content_type: text/plain
      - name: Add build_meta.json       
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release_gen/build_meta.json                                                           
          asset_name: build_meta.json                                     
          asset_content_type: application/json
      - name: Announce build_meta.json download url to other jobs
        run: |
          cd release_gen
          chmod +x announce_build_meta.sh
          ./announce_build_meta.sh ${{ github.repository }}

  build-linux-amd64:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        run: |
          chmod +x compile_linux.sh
          ./compile_linux.sh amd64 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      - name: Export distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: out/binary_distrib.tar.gz
          asset_name: linux-amd64.tar.gz
          asset_content_type: application/octet-stream


  build-linux-i386:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        run: |
          chmod +x compile_linux.sh
          ./compile_linux.sh 386 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      - name: Export distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: out/binary_distrib.tar.gz
          asset_name: linux-i386.tar.gz
          asset_content_type: application/octet-stream


  build-linux-arm64:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        run: |
          chmod +x compile_linux.sh
          ./compile_linux.sh arm64 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      - name: Export distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: out/binary_distrib.tar.gz
          asset_name: linux-arm64.tar.gz
          asset_content_type: application/octet-stream
          
          
  build-linux-arm:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        run: |
          chmod +x compile_linux.sh
          ./compile_linux.sh arm/v6 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      - name: Export distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: out/binary_distrib.tar.gz
          asset_name: linux-arm.tar.gz
          asset_content_type: application/octet-stream


  build-windows-amd64:
    runs-on: windows-2019
    needs: create-release
    steps:
      - uses: actions/checkout@v1
      -
        name: Build
        shell: cmd
        run: |
          compile_windows.bat amd64 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      - name: Export distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: out/binary_distrib.tar.gz
          asset_name: windows-amd64.tar.gz
          asset_content_type: application/octet-stream


  build-windows-i386:
    runs-on: windows-2019
    needs: create-release
    steps:
      - uses: actions/checkout@v1
      -
        name: Build
        shell: cmd
        run: |
          compile_windows.bat 386 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      - name: Export distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: out/binary_distrib.tar.gz
          asset_name: windows-i386.tar.gz
          asset_content_type: application/octet-stream
          
  
  build-windows-arm64:
    runs-on: windows-2019
    needs: create-release
    steps:
      - uses: actions/checkout@v1
      -
        name: Build
        shell: cmd
        run: |
          compile_windows.bat arm64 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      - name: Export distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: out/binary_distrib.tar.gz
          asset_name: windows-arm64.tar.gz
          asset_content_type: application/octet-stream
